package in.ashokeit.service;

import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Random;

import org.springframework.beans.BeanUtils;
import org.springframework.stereotype.Service;

import in.ashokeit.binding.Passanger;
import in.ashokeit.binding.Ticket;
@Service
public class TicketServiceImpl implements TicketService {
   //we are deploying this aplication in cloud hence database not taken
  // hence map is taken as database as in cloud db is not available
	Map<Integer, Ticket> db=new HashMap<>(); //global object
	
	@Override
	public Ticket bookTicket(Passanger passanger) {
		Ticket ticket=new Ticket();
		Random r=new Random();
		int id = r.nextInt(5000); //no <5000
		ticket.setTicketNum(id); //not inserting in database hence 
		                         //taken manually else autogenerated
		BeanUtils.copyProperties(passanger, ticket);//to copy passanger data 
		ticket.setStatus("Confirmed");              //comming into ticket object
		db.put(id, ticket);
		
		return ticket;
	}

	@Override
	public Collection<Ticket> getAllTickets() {
		Collection<Ticket> values = db.values();
		return values;
	}
	

}
